### ISSUE TITLE
Checkbox and label are not displayed correct, especially on smartphone

### ISSUE THREAD

**Issue by lebenspraxis** [stcr/subscribe-to-comments-reloaded#422]
Hello,
after installing stcr vs. 180225 I can't get the box and label get placed correct. It seems as if there were colums in the commentform and the stcr field is only placed in one of these columns.

I have wordpress 4.9.6, theme enfold, php 7.2 and MySQL 5.5 database. See the single blog pages on my blog
<a href="https://www.lebenspraxis.com/blog">www.lebenspraxis.com/blog</a>

Took 3 sreenshots, so you can see what I mean and you can see my plugin-settings for the checkbox and label. One screenshot of the desktop, one of the smartphone display, one settings.

![screenshot 22](https://user-images.githubusercontent.com/39678839/40590046-931f6c1a-61f8-11e8-947f-fc11ca32a965.png)

![screenshot_2018-05-27-21-08-18-254_org mozilla firefox](https://user-images.githubusercontent.com/39678839/40589991-bbc02c3c-61f7-11e8-8bd4-61ca32d16e5b.png)
![screenshot 23](https://user-images.githubusercontent.com/39678839/40590104-6fcbc37a-61f9-11e8-9e89-d0318ca46cfb.png)

I saw that a user on the wordpress plugin page seems to have the same issue.

Best regards,
lebenspraxis

**Comment by Raffaele3D** [comment]
Yes...it is me!

In my case the plug in is not displayed at all!

**Comment by lebenspraxis** [comment]
@Raffaele3D : I'm not sure what you mean. I refered to [this users entry ](https://wordpress.org/support/topic/description-of-the-checkbox-is-columnar/) in the wordpress plugin support forum. That seems to be the same issue as mine.
I don't know what you mean in writing "the plug in is not displayed at all".  I had also the situation that the checkbox and label weren't displayed. I tried some changes in the settings and in the html-field and yes, I found that sometimes nothing was displayed.

**Comment by Raffaele3D** [comment]
Dear @lebenspraxis 
Thanks for replying.

I have installed the plug in on Wordpress 4.9.6 but checkbox and list selection are not displayed!

If I am logged in as administrator the author label "**You can manage the subscriptions of this post.**" is properly displayed, but if I am not logged as administrator neither checkbox or list selection are displayed: please refer to the ettachment
![02](https://user-images.githubusercontent.com/17453876/40772672-91aa844c-64b8-11e8-856c-9bb6745e0146.jpg)

I am running the theme **Newsmax** on my web site.

Actually the plugin is up and running and this are the settings:
![01](https://user-images.githubusercontent.com/17453876/40772691-a49c0d96-64b8-11e8-9222-35cf309d473c.jpg)
but nothing is displayed!

Could you be so kind to tell me which are the settings that properly work for the HTML field?

Thanks in advance!

**Comment by lebenspraxis** [comment]
Hey @Raffaele3D,

I don't know what may work. My skills are limited. I only tried some things and did end up with the default settings of the field. I found out that it is possible to get the box a little bit more to the left side by setting a minus value of css "position absolute; left: -xy". But that's no real solution for me, so I will wait till anybody of the stcr-team supports this issue.
What works fine is to get the text of the label vertically aligned with css "float:left;clear:left;". I have that in the inline-css-styles-setting of the comments form panel.
For you: If you set the "STCR Position" in the Options Panel to "No", I think the checkbox and it's label will display. But: You then may really have the same issue as me. To place the stcr checkbox and label above the submit button it might be possible to manipulate the button itself so that it is displayed further down. Maybe the support of your theme can give you some css for that.
Besides that, this all is about trying to somehow correct the not suitable code of the stcr plugin that causes this issues. The better way at least is that the support works on that.

Best regards,
lebenspraxis

**Comment by Reedyseth** [comment]
Hi Guys, sorry for being late to the party. We have two thread going on here, The Checkbox styles and the problem with the checkbox not appearing. First I will help you with the CSS style.

Regards.!!

**Comment by Reedyseth** [comment]
@lebenspraxis the issue with you style is that your theme is applying a `left` position of `245px`, so just setting that to zero and you will get the label in the correct position
```html
<p class='comment-form-subscriptions'><label for='subscribe-reloaded' style="left: 0;">[checkbox_field] [checkbox_label]</label></p>
```
![image](https://user-images.githubusercontent.com/1228711/40841905-4cbd4ea8-6569-11e8-8b8f-05abbf1e649f.png)

**Comment by Raffaele3D** [comment]
Hi @lebenspraxis 

Thanks to attend our party! :)

I have fixed my problem adding this line to my comments.php file

`<?php global $wp_subscribe_reloaded; if (isset($wp_subscribe_reloaded)){ $wp_subscribe_reloaded->stcr->subscribe_reloaded_show(); } ?>`

but, unfortunately, other **# 2 BIG ISSUES** have risen!

1. The option that the user select into the drop down list is COMPLETELY IGNORED: it is overwritten by the option in the COMMENT FORM SETUP PANEL. In this case I have selected the option "All" in my browser (see image below) 
![01](https://user-images.githubusercontent.com/17453876/40847409-335ffd16-65b4-11e8-86ab-adcd6cc40f24.jpg)
but when the subscription list is updated by the system, it does not match the option selected by the user in the browser (see image below) 
![02](https://user-images.githubusercontent.com/17453876/40847542-9aab48fe-65b4-11e8-9f5f-c6fa18d86b3c.jpg)

2. Once the user has subscribed the comment, the subscribed label "You are subscribed to this post. Manage  your subscriptions." is never shown  (see image below) 
   
![03](https://user-images.githubusercontent.com/17453876/40848110-25a963c2-65b6-11e8-9ef8-6dbbaec6986b.jpg)

Thanks in advance!

**Comment by Reedyseth** [comment]
@Raffaele3D You issue is different from @lebenspraxis So I have remove your messages and created a new issue for it -> https://github.com/stcr/subscribe-to-comments-reloaded/issues/424.

**Comment by lebenspraxis** [comment]
Thank you so much Reedyseth!
The checkbox and label are on the right position now. I still have some trouble with the appearance on smartphones. There's not enough space to the submit button. And above all half of the label's text aligns with the submit button and some words seem to disappear behind the button. Don't know why. Look at this:
![screenshot_2018-06-02-00-00-25-311_org mozilla firefox](https://user-images.githubusercontent.com/39678839/40865694-eecaaa84-65f9-11e8-9e8e-bdc3e06c8479.png)

Best regards,
lebenspraxis

**Comment by Reedyseth** [comment]
The position of your submit button needs to have a little bit more, take a look at the screen.

![image](https://user-images.githubusercontent.com/1228711/40866105-38ec99ce-65b9-11e8-9a99-8773afc00a2e.png)

![image](https://user-images.githubusercontent.com/1228711/40866133-53bc7846-65b9-11e8-90a2-2839e557c7a0.png)

**Comment by lebenspraxis** [comment]
Hello Reedyseth,
I just wanted to tell you that meanwhile I could solve all issues I had. Thank you very much for your last hint and your support! Helped a lot.

Best regards,
lebenspraxis

**Comment by Reedyseth** [comment]
You're Welcome !!
